- name: Install Linux dependencies
  if: runner.os == 'Linux'
  run: |
    sudo apt-get update
    sudo apt-get install -y \
      libasound2-dev \
      libudev-dev \
      libwayland-dev \
      libxkbcommon-dev \
      libx11-dev \
      libxcursor-dev \
      libxi-dev \
      libxrandr-dev \
      libxinerama-dev \
      libegl1-mesa-dev \
      libgles2-mesa-dev \
      libdbus-1-dev \
      pkg-config
