import { SettingsState } from "../../settings_state.slint";
import { Theme } from "../../theme.slint";
import { ScrollView, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { MenuButton } from "widgets.slint";
import { GraphicsTab } from "graphics.slint";
import { ControlsTab } from "controls.slint";
import { BasePanel } from "../base_panel.slint";

export component SettingsPanel inherits BasePanel {
    in-out property <int> active-tab: 0;
    title: "Settings";
    close => {
        SettingsState.show-settings = false;
    }
    TouchArea {
        scroll-event(event) => {
            accept
        }
    }

    VerticalBox {
        padding-left: 12px;
        padding-right: 12px;
        padding-top: 2px;
        padding-bottom: 12px;
        spacing: 8px;
        HorizontalBox {
            spacing: 12px;
            VerticalBox {
                width: 140px;
                spacing: 6px;
                MenuButton {
                    label: "Graphics";
                    selected: active-tab == 0;
                    clicked => {
                        active-tab = 0;
                    }
                }

                MenuButton {
                    label: "Controls";
                    selected: active-tab == 1;
                    clicked => {
                        active-tab = 1;
                    }
                }
            }

            Rectangle {
                width: 1px;
                background: Theme.border-subtle;
            }

            Rectangle {
                height: 440px;
                if active-tab == 0: ScrollView {
                    viewport-width: self.visible-width;
                    GraphicsTab {
                        alignment: start;
                    }
                }
                if active-tab == 1: ScrollView {
                    viewport-width: self.visible-width;
                    ControlsTab {
                        alignment: start;
                    }
                }
            }
        }
    }
}
