[package]
name = "rendering"
version.workspace = true
edition.workspace = true

[dependencies]
formats.workspace = true
bevy_math.workspace = true
bytemuck.workspace = true
anyhow.workspace = true
etagere = "0.3"
rangemap.workspace = true
oxicode.workspace = true
byteorder.workspace = true
ktx2.workspace = true
wgpu.workspace = true
tracing.workspace = true
num_enum.workspace = true
rustc-hash = "2.1.1"
rand.workspace = true

[dev-dependencies]
naga = "29"
pollster = "1.0"
