import { NpcDialogState, MenuEntry } from "../game_state.slint";
import { ScrollView, LineEdit, VerticalBox } from "std-widgets.slint";
import { Theme } from "../theme.slint";
import { Icon } from "icon.slint";


import "../fonts/Lato-Regular.ttf";
import "../fonts/Lato-Light.ttf";
import "../fonts/Lato-Thin.ttf";
import "../fonts/Lato-Bold.ttf";
import "../fonts/Lato-Black.ttf";
import "../fonts/Lato-Italic.ttf";
import "../fonts/Lato-LightItalic.ttf";
import "../fonts/Lato-ThinItalic.ttf";
import "../fonts/Lato-BoldItalic.ttf";
import "../fonts/Lato-BlackItalic.ttf";

export component NpcDialog inherits Rectangle {
    property <image> npc-portrait: NpcDialogState.data.npc_portrait;
    TouchArea {
        clicked => {
            NpcDialogState.close();
        }
    }

    background: #0007;

    if (!NpcDialogState.data.interaction_enabled): TouchArea {
        z: 100;
    }

    HorizontalLayout {
        alignment: center;
        VerticalLayout {
            alignment: end;
            preferred-width: 660px;
            HorizontalLayout {
                alignment: center;
                z: 10;
                VerticalLayout {
                    alignment: end;
                    preferred-width: 660px;
                    HorizontalLayout {
                        padding-left: 32px;
                        padding-right: self.padding-left;
                        spacing: 8px;

                        // Portrait
                    VerticalLayout {
                            alignment: end;
                            if (npc-portrait.width > 100): Image {
                                source: npc-portrait;
                                height: self.width / (self.source.width / self.source.height);
                                preferred-width: 320px;
                                image-fit: ImageFit.contain;
                            }
                            if (npc-portrait.width <= 100 && npc-portrait.width > 0): HorizontalLayout {
                                alignment: center;
                                Image {
                                    source: npc-portrait;
                                    width: self.source.width * 2px;
                                    height: self.source.height * 2px;
                                    image-fit: ImageFit.contain;
                                    image-rendering: pixelated;
                                }
                            }
                            HorizontalLayout {
                                height: 0px;
                                padding-top: -18px;
                                Rectangle {
                                    height: 36px;
                                    background: #28210F;
                                    Image {
                                        width: parent.width;
                                        height: parent.height;
                                        source: @image-url("../panel/Default/Panel/panel-007.png", nine-slice(18));
                                        colorize: #6c3f1c;
                                    }

                                    HorizontalLayout {
                                        alignment: center;
                                        padding-left: 32px;
                                        padding-right: self.padding-left;
                                        portrait-npc-name := Text {
                                            font-family: "Lato";
                                            font-size: 20px;
                                            text: NpcDialogState.data.npc_name;
                                            vertical-alignment: center;
                                            font-weight: 500;
                                        }
                                    }
                                }
                            }
                        }

                        Rectangle { }

                        // Menu options
                        VerticalLayout {
                            opacity: NpcDialogState.data.interaction_enabled ? 1.0 : 0.6;
                            animate opacity { duration: 150ms; }
                            alignment: end;
                            if (NpcDialogState.data.text_entry_visible): VerticalLayout {
                                Rectangle {
                                    background: @linear-gradient(0deg, #0000 0%, #0007 15%, #0007 85%, #0000 100%);
                                    preferred-height: 240px;
                                    width: 260px;
                                    VerticalLayout {
                                        padding: 16px;
                                        spacing: 12px;
                                        alignment: center;
                                        if NpcDialogState.data.text_entry_args != "": Rectangle {
                                            height: 32px;
                                            background: #FFC04010;
                                            border-radius: 6px;
                                            border-width: 1px;
                                            border-color: #FFC04030;
                                            Text {
                                                text: NpcDialogState.data.text_entry_args;
                                                font-size: 13px;
                                                font-weight: 500;
                                                color: Theme.accent;
                                                horizontal-alignment: center;
                                                vertical-alignment: center;
                                            }
                                        }
                                        npc-input := LineEdit {
                                            height: 36px;
                                            placeholder-text: NpcDialogState.data.text_entry_prompt != "" ? NpcDialogState.data.text_entry_prompt : "Type here...";
                                            accepted => {
                                                if self.text != "" {
                                                    NpcDialogState.submit-text(self.text);
                                                    self.text = "";
                                                }
                                            }
                                        }

                                        Rectangle {
                                            height: 36px;
                                            border-radius: 6px;
                                            background: npc-input.text == "" ? #FFC04008 : submit-touch.pressed ? #FFC04050 : submit-touch.has-hover ? #FFC04030 : #FFC04018;
                                            border-width: 1px;
                                            border-color: #FFC04050;
                                            opacity: npc-input.text == "" ? 0.5 : 1.0;
                                            submit-touch := TouchArea {
                                                mouse-cursor: npc-input.text != "" ? pointer : default;
                                                clicked => {
                                                    if npc-input.text != "" {
                                                        NpcDialogState.submit-text(npc-input.text);
                                                        npc-input.text = "";
                                                    }
                                                }
                                            }

                                            Text {
                                                text: "Submit";
                                                font-size: 13px;
                                                font-weight: 500;
                                                color: Theme.accent;
                                                horizontal-alignment: center;
                                                vertical-alignment: center;
                                            }
                                        }
                                    }
                                }
                            }
                            if (!NpcDialogState.data.is_shop && NpcDialogState.data.menu_entries.length > 0): VerticalLayout {
                                Rectangle {
                                    background: @linear-gradient(0deg, #0000 0%, #0007 15%, #0007 85%, #0000 100%);
                                    VerticalLayout {
                                        padding: 24px;
                                        for entry in NpcDialogState.data.menu_entries: Rectangle {
                                            animate background { duration: 100ms; }
                                            touch := TouchArea {
                                                mouse-cursor: pointer;
                                                clicked => {
                                                    NpcDialogState.select-option(entry.id, entry.text);
                                                }
                                            }

                                            HorizontalLayout {
                                                padding: 22px;
                                                padding-top: 6px;
                                                padding-bottom: self.padding-top;
                                                Text {
                                                    text: entry.text;
                                                    font-size: 14px;
                                                    font-family: "Lato";
                                                    color: Theme.foreground;
                                                    horizontal-alignment: left;
                                                    font-weight: 700;
                                                    font-italic: true;
                                                }
                                            }

                                            states [
                                                hover when touch.has-hover: {
                                                    background: #ffffff10;
                                                }
                                            ]
                                        }
                                    }
                                }
                            }
                            if (NpcDialogState.data.is_shop && NpcDialogState.data.menu_entries.length > 0): VerticalLayout {
                                Rectangle {
                                    background: @linear-gradient(0deg, #0000 0%, #0007 15%, #0007 85%, #0000 100%);
                                    preferred-height: 240px;
                                    width: 260px;
                                    ScrollView {
                                        GridLayout {
                                            spacing: 10px;
                                            padding: 5px;
                                            for entry[idx] in NpcDialogState.data.menu_entries: Rectangle {
                                                row: Math.floor(idx / 2);
                                                item-touch := TouchArea {
                                                    mouse-cursor: pointer;
                                                    clicked => {
                                                        NpcDialogState.select-option(entry.id, entry.text);
                                                    }
                                                }

                                                HorizontalLayout {
                                                    padding-left: 4px;
                                                    padding-right: 8px;
                                                    spacing: 8px;
                                                    Rectangle {
                                                        width: 28px;
                                                        height: 28px;
                                                        y: (parent.height - self.height) / 2;
                                                        background: #00000040;
                                                        border-radius: 3px;
                                                        Icon {
                                                            icon: entry.icon;
                                                            x: (parent.width - self.width) / 2;
                                                            y: (parent.height - self.height) / 2;
                                                        }
                                                    }

                                                    VerticalLayout {
                                                        alignment: center;
                                                        spacing: 1px;
                                                        Text {
                                                            text: entry.text;
                                                            font-size: 11px;
                                                            color: #e0e0e0;
                                                            overflow: elide;
                                                        }

                                                        if entry.cost > 0: Text {
                                                            text: entry.cost;
                                                            font-size: 9px;
                                                            color: #ffc040;
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }

            Rectangle {
                background: #f5dec2;
                preferred-height: 80px;
                Image {
                    width: parent.width;
                    height: parent.height;
                    source: @image-url("../panel/Default/Panel/panel-014.png", nine-slice(16));
                    colorize: #b08869;
                }

                VerticalLayout {
                    alignment: center;
                    padding: 24px;
                    padding-top: 32px;
                    ScrollView {
                        height: min(text-content.height, 140px);
                        viewport-height: text-content.height;
                        text-content := Text {
                            width: 100%;
                            font-family: "Lato";
                            font-size: 16px;
                            font-weight: 700;
                            text: NpcDialogState.data.dialog_text;
                            wrap: word-wrap;
                            color: #28210F;
                        }
                    }
                }
            }

            Rectangle {
                preferred-height: 120px;
            }
        }
    }
}
