#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum GameAction {
    MoveUp,
    MoveDown,
    MoveLeft,
    MoveRight,
    Inventory,
    Skills,
    Spells,
    Settings,
    Refresh,
    BasicAttack,
    HotbarSlot1,
    HotbarSlot2,
    HotbarSlot3,
    HotbarSlot4,
    HotbarSlot5,
    HotbarSlot6,
    HotbarSlot7,
    HotbarSlot8,
    HotbarSlot9,
    HotbarSlot10,
    HotbarSlot11,
    HotbarSlot12,
    SwitchToInventory,
    SwitchToSkills,
    SwitchToSpells,
    SwitchToHotbar1,
    SwitchToHotbar2,
    SwitchToHotbar3,
}

impl GameAction {
    pub fn all() -> &'static [GameAction] {
        &[
            GameAction::MoveUp,
            GameAction::MoveDown,
            GameAction::MoveLeft,
            GameAction::MoveRight,
            GameAction::Inventory,
            GameAction::Skills,
            GameAction::Spells,
            GameAction::Settings,
            GameAction::Refresh,
            GameAction::BasicAttack,
            GameAction::HotbarSlot1,
            GameAction::HotbarSlot2,
            GameAction::HotbarSlot3,
            GameAction::HotbarSlot4,
            GameAction::HotbarSlot5,
            GameAction::HotbarSlot6,
            GameAction::HotbarSlot7,
            GameAction::HotbarSlot8,
            GameAction::HotbarSlot9,
            GameAction::HotbarSlot10,
            GameAction::HotbarSlot11,
            GameAction::HotbarSlot12,
            GameAction::SwitchToInventory,
            GameAction::SwitchToSkills,
            GameAction::SwitchToSpells,
            GameAction::SwitchToHotbar1,
            GameAction::SwitchToHotbar2,
            GameAction::SwitchToHotbar3,
        ]
    }

    pub fn action_id(&self) -> &'static str {
        match self {
            GameAction::MoveUp => "move_up",
            GameAction::MoveDown => "move_down",
            GameAction::MoveLeft => "move_left",
            GameAction::MoveRight => "move_right",
            GameAction::Inventory => "inventory",
            GameAction::Skills => "skills",
            GameAction::Spells => "spells",
            GameAction::Settings => "settings",
            GameAction::Refresh => "refresh",
            GameAction::BasicAttack => "basic_attack",
            GameAction::HotbarSlot1 => "hotbar_slot_1",
            GameAction::HotbarSlot2 => "hotbar_slot_2",
            GameAction::HotbarSlot3 => "hotbar_slot_3",
            GameAction::HotbarSlot4 => "hotbar_slot_4",
            GameAction::HotbarSlot5 => "hotbar_slot_5",
            GameAction::HotbarSlot6 => "hotbar_slot_6",
            GameAction::HotbarSlot7 => "hotbar_slot_7",
            GameAction::HotbarSlot8 => "hotbar_slot_8",
            GameAction::HotbarSlot9 => "hotbar_slot_9",
            GameAction::HotbarSlot10 => "hotbar_slot_10",
            GameAction::HotbarSlot11 => "hotbar_slot_11",
            GameAction::HotbarSlot12 => "hotbar_slot_12",
            GameAction::SwitchToInventory => "switch_to_inventory",
            GameAction::SwitchToSkills => "switch_to_skills",
            GameAction::SwitchToSpells => "switch_to_spells",
            GameAction::SwitchToHotbar1 => "switch_to_hotbar_1",
            GameAction::SwitchToHotbar2 => "switch_to_hotbar_2",
            GameAction::SwitchToHotbar3 => "switch_to_hotbar_3",
        }
    }

    pub fn from_action_id(id: &str) -> Option<Self> {
        match id {
            "move_up" => Some(GameAction::MoveUp),
            "move_down" => Some(GameAction::MoveDown),
            "move_left" => Some(GameAction::MoveLeft),
            "move_right" => Some(GameAction::MoveRight),
            "inventory" => Some(GameAction::Inventory),
            "skills" => Some(GameAction::Skills),
            "spells" => Some(GameAction::Spells),
            "settings" => Some(GameAction::Settings),
            "refresh" => Some(GameAction::Refresh),
            "basic_attack" => Some(GameAction::BasicAttack),
            "hotbar_slot_1" => Some(GameAction::HotbarSlot1),
            "hotbar_slot_2" => Some(GameAction::HotbarSlot2),
            "hotbar_slot_3" => Some(GameAction::HotbarSlot3),
            "hotbar_slot_4" => Some(GameAction::HotbarSlot4),
            "hotbar_slot_5" => Some(GameAction::HotbarSlot5),
            "hotbar_slot_6" => Some(GameAction::HotbarSlot6),
            "hotbar_slot_7" => Some(GameAction::HotbarSlot7),
            "hotbar_slot_8" => Some(GameAction::HotbarSlot8),
            "hotbar_slot_9" => Some(GameAction::HotbarSlot9),
            "hotbar_slot_10" => Some(GameAction::HotbarSlot10),
            "hotbar_slot_11" => Some(GameAction::HotbarSlot11),
            "hotbar_slot_12" => Some(GameAction::HotbarSlot12),
            "switch_to_inventory" => Some(GameAction::SwitchToInventory),
            "switch_to_skills" => Some(GameAction::SwitchToSkills),
            "switch_to_spells" => Some(GameAction::SwitchToSpells),
            "switch_to_hotbar_1" => Some(GameAction::SwitchToHotbar1),
            "switch_to_hotbar_2" => Some(GameAction::SwitchToHotbar2),
            "switch_to_hotbar_3" => Some(GameAction::SwitchToHotbar3),
            _ => None,
        }
    }

    pub fn label(&self) -> &'static str {
        match self {
            GameAction::MoveUp => "Move Up",
            GameAction::MoveDown => "Move Down",
            GameAction::MoveLeft => "Move Left",
            GameAction::MoveRight => "Move Right",
            GameAction::Inventory => "Inventory",
            GameAction::Skills => "Skills",
            GameAction::Spells => "Spells",
            GameAction::Settings => "Settings",
            GameAction::Refresh => "Refresh",
            GameAction::BasicAttack => "Basic Attack",
            GameAction::HotbarSlot1 => "Slot 1",
            GameAction::HotbarSlot2 => "Slot 2",
            GameAction::HotbarSlot3 => "Slot 3",
            GameAction::HotbarSlot4 => "Slot 4",
            GameAction::HotbarSlot5 => "Slot 5",
            GameAction::HotbarSlot6 => "Slot 6",
            GameAction::HotbarSlot7 => "Slot 7",
            GameAction::HotbarSlot8 => "Slot 8",
            GameAction::HotbarSlot9 => "Slot 9",
            GameAction::HotbarSlot10 => "Slot 10",
            GameAction::HotbarSlot11 => "Slot 11",
            GameAction::HotbarSlot12 => "Slot 12",
            GameAction::SwitchToInventory => "Inventory Panel",
            GameAction::SwitchToSkills => "Skills Panel",
            GameAction::SwitchToSpells => "Spells Panel",
            GameAction::SwitchToHotbar1 => "Hotbar 1",
            GameAction::SwitchToHotbar2 => "Hotbar 2",
            GameAction::SwitchToHotbar3 => "Hotbar 3",
        }
    }
}
