#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum GameAction {
    MoveUp,
    MoveDown,
    MoveLeft,
    MoveRight,
    Inventory,
    Skills,
    Spells,
    Settings,
    Refresh,
    ToggleOverview,
    BasicAttack,
    AutoAttackToggle,
    ItemPickupBelow,
    HotbarSlot1,
    HotbarSlot2,
    HotbarSlot3,
    HotbarSlot4,
    HotbarSlot5,
    HotbarSlot6,
    HotbarSlot7,
    HotbarSlot8,
    HotbarSlot9,
    HotbarSlot10,
    HotbarSlot11,
    HotbarSlot12,
    HotbarSlot13,
    HotbarSlot14,
    HotbarSlot15,
    HotbarSlot16,
    HotbarSlot17,
    HotbarSlot18,
    HotbarSlot19,
    HotbarSlot20,
    HotbarSlot21,
    HotbarSlot22,
    HotbarSlot23,
    HotbarSlot24,
    HotbarSlot25,
    HotbarSlot26,
    HotbarSlot27,
    HotbarSlot28,
    HotbarSlot29,
    HotbarSlot30,
    HotbarSlot31,
    HotbarSlot32,
    HotbarSlot33,
    HotbarSlot34,
    HotbarSlot35,
    HotbarSlot36,
    HotbarSlot37,
    HotbarSlot38,
    HotbarSlot39,
    HotbarSlot40,
    HotbarSlot41,
    HotbarSlot42,
    HotbarSlot43,
    HotbarSlot44,
    HotbarSlot45,
    HotbarSlot46,
    HotbarSlot47,
    HotbarSlot48,
    SwitchToInventory,
    SwitchToSkills,
    SwitchToSpells,
    SwitchToHotbar1,
    SwitchToHotbar2,
    SwitchToHotbar3,
}

impl GameAction {
    pub fn all() -> &'static [GameAction] {
        &[
            GameAction::MoveUp,
            GameAction::MoveDown,
            GameAction::MoveLeft,
            GameAction::MoveRight,
            GameAction::Inventory,
            GameAction::Skills,
            GameAction::Spells,
            GameAction::Settings,
            GameAction::Refresh,
            GameAction::ToggleOverview,
            GameAction::BasicAttack,
            GameAction::AutoAttackToggle,
            GameAction::ItemPickupBelow,
            GameAction::HotbarSlot1,
            GameAction::HotbarSlot2,
            GameAction::HotbarSlot3,
            GameAction::HotbarSlot4,
            GameAction::HotbarSlot5,
            GameAction::HotbarSlot6,
            GameAction::HotbarSlot7,
            GameAction::HotbarSlot8,
            GameAction::HotbarSlot9,
            GameAction::HotbarSlot10,
            GameAction::HotbarSlot11,
            GameAction::HotbarSlot12,
            GameAction::HotbarSlot13,
            GameAction::HotbarSlot14,
            GameAction::HotbarSlot15,
            GameAction::HotbarSlot16,
            GameAction::HotbarSlot17,
            GameAction::HotbarSlot18,
            GameAction::HotbarSlot19,
            GameAction::HotbarSlot20,
            GameAction::HotbarSlot21,
            GameAction::HotbarSlot22,
            GameAction::HotbarSlot23,
            GameAction::HotbarSlot24,
            GameAction::HotbarSlot25,
            GameAction::HotbarSlot26,
            GameAction::HotbarSlot27,
            GameAction::HotbarSlot28,
            GameAction::HotbarSlot29,
            GameAction::HotbarSlot30,
            GameAction::HotbarSlot31,
            GameAction::HotbarSlot32,
            GameAction::HotbarSlot33,
            GameAction::HotbarSlot34,
            GameAction::HotbarSlot35,
            GameAction::HotbarSlot36,
            GameAction::HotbarSlot37,
            GameAction::HotbarSlot38,
            GameAction::HotbarSlot39,
            GameAction::HotbarSlot40,
            GameAction::HotbarSlot41,
            GameAction::HotbarSlot42,
            GameAction::HotbarSlot43,
            GameAction::HotbarSlot44,
            GameAction::HotbarSlot45,
            GameAction::HotbarSlot46,
            GameAction::HotbarSlot47,
            GameAction::HotbarSlot48,
            GameAction::SwitchToInventory,
            GameAction::SwitchToSkills,
            GameAction::SwitchToSpells,
            GameAction::SwitchToHotbar1,
            GameAction::SwitchToHotbar2,
            GameAction::SwitchToHotbar3,
        ]
    }

    pub fn action_id(&self) -> &'static str {
        match self {
            GameAction::MoveUp => "move_up",
            GameAction::MoveDown => "move_down",
            GameAction::MoveLeft => "move_left",
            GameAction::MoveRight => "move_right",
            GameAction::Inventory => "inventory",
            GameAction::Skills => "skills",
            GameAction::Spells => "spells",
            GameAction::Settings => "settings",
            GameAction::Refresh => "refresh",
            GameAction::ToggleOverview => "toggle_overview",
            GameAction::BasicAttack => "basic_attack",
            GameAction::AutoAttackToggle => "auto_attack_toggle",
            GameAction::ItemPickupBelow => "item_pickup_below",
            GameAction::HotbarSlot1 => "hotbar_slot_1",
            GameAction::HotbarSlot2 => "hotbar_slot_2",
            GameAction::HotbarSlot3 => "hotbar_slot_3",
            GameAction::HotbarSlot4 => "hotbar_slot_4",
            GameAction::HotbarSlot5 => "hotbar_slot_5",
            GameAction::HotbarSlot6 => "hotbar_slot_6",
            GameAction::HotbarSlot7 => "hotbar_slot_7",
            GameAction::HotbarSlot8 => "hotbar_slot_8",
            GameAction::HotbarSlot9 => "hotbar_slot_9",
            GameAction::HotbarSlot10 => "hotbar_slot_10",
            GameAction::HotbarSlot11 => "hotbar_slot_11",
            GameAction::HotbarSlot12 => "hotbar_slot_12",
            GameAction::HotbarSlot13 => "hotbar_slot_13",
            GameAction::HotbarSlot14 => "hotbar_slot_14",
            GameAction::HotbarSlot15 => "hotbar_slot_15",
            GameAction::HotbarSlot16 => "hotbar_slot_16",
            GameAction::HotbarSlot17 => "hotbar_slot_17",
            GameAction::HotbarSlot18 => "hotbar_slot_18",
            GameAction::HotbarSlot19 => "hotbar_slot_19",
            GameAction::HotbarSlot20 => "hotbar_slot_20",
            GameAction::HotbarSlot21 => "hotbar_slot_21",
            GameAction::HotbarSlot22 => "hotbar_slot_22",
            GameAction::HotbarSlot23 => "hotbar_slot_23",
            GameAction::HotbarSlot24 => "hotbar_slot_24",
            GameAction::HotbarSlot25 => "hotbar_slot_25",
            GameAction::HotbarSlot26 => "hotbar_slot_26",
            GameAction::HotbarSlot27 => "hotbar_slot_27",
            GameAction::HotbarSlot28 => "hotbar_slot_28",
            GameAction::HotbarSlot29 => "hotbar_slot_29",
            GameAction::HotbarSlot30 => "hotbar_slot_30",
            GameAction::HotbarSlot31 => "hotbar_slot_31",
            GameAction::HotbarSlot32 => "hotbar_slot_32",
            GameAction::HotbarSlot33 => "hotbar_slot_33",
            GameAction::HotbarSlot34 => "hotbar_slot_34",
            GameAction::HotbarSlot35 => "hotbar_slot_35",
            GameAction::HotbarSlot36 => "hotbar_slot_36",
            GameAction::HotbarSlot37 => "hotbar_slot_37",
            GameAction::HotbarSlot38 => "hotbar_slot_38",
            GameAction::HotbarSlot39 => "hotbar_slot_39",
            GameAction::HotbarSlot40 => "hotbar_slot_40",
            GameAction::HotbarSlot41 => "hotbar_slot_41",
            GameAction::HotbarSlot42 => "hotbar_slot_42",
            GameAction::HotbarSlot43 => "hotbar_slot_43",
            GameAction::HotbarSlot44 => "hotbar_slot_44",
            GameAction::HotbarSlot45 => "hotbar_slot_45",
            GameAction::HotbarSlot46 => "hotbar_slot_46",
            GameAction::HotbarSlot47 => "hotbar_slot_47",
            GameAction::HotbarSlot48 => "hotbar_slot_48",
            GameAction::SwitchToInventory => "switch_to_inventory",
            GameAction::SwitchToSkills => "switch_to_skills",
            GameAction::SwitchToSpells => "switch_to_spells",
            GameAction::SwitchToHotbar1 => "switch_to_hotbar_1",
            GameAction::SwitchToHotbar2 => "switch_to_hotbar_2",
            GameAction::SwitchToHotbar3 => "switch_to_hotbar_3",
        }
    }

    pub fn from_action_id(id: &str) -> Option<Self> {
        match id {
            "move_up" => Some(GameAction::MoveUp),
            "move_down" => Some(GameAction::MoveDown),
            "move_left" => Some(GameAction::MoveLeft),
            "move_right" => Some(GameAction::MoveRight),
            "inventory" => Some(GameAction::Inventory),
            "skills" => Some(GameAction::Skills),
            "spells" => Some(GameAction::Spells),
            "settings" => Some(GameAction::Settings),
            "refresh" => Some(GameAction::Refresh),
            "toggle_overview" => Some(GameAction::ToggleOverview),
            "basic_attack" => Some(GameAction::BasicAttack),
            "auto_attack_toggle" => Some(GameAction::AutoAttackToggle),
            "item_pickup_below" => Some(GameAction::ItemPickupBelow),
            "hotbar_slot_1" => Some(GameAction::HotbarSlot1),
            "hotbar_slot_2" => Some(GameAction::HotbarSlot2),
            "hotbar_slot_3" => Some(GameAction::HotbarSlot3),
            "hotbar_slot_4" => Some(GameAction::HotbarSlot4),
            "hotbar_slot_5" => Some(GameAction::HotbarSlot5),
            "hotbar_slot_6" => Some(GameAction::HotbarSlot6),
            "hotbar_slot_7" => Some(GameAction::HotbarSlot7),
            "hotbar_slot_8" => Some(GameAction::HotbarSlot8),
            "hotbar_slot_9" => Some(GameAction::HotbarSlot9),
            "hotbar_slot_10" => Some(GameAction::HotbarSlot10),
            "hotbar_slot_11" => Some(GameAction::HotbarSlot11),
            "hotbar_slot_12" => Some(GameAction::HotbarSlot12),
            "hotbar_slot_13" => Some(GameAction::HotbarSlot13),
            "hotbar_slot_14" => Some(GameAction::HotbarSlot14),
            "hotbar_slot_15" => Some(GameAction::HotbarSlot15),
            "hotbar_slot_16" => Some(GameAction::HotbarSlot16),
            "hotbar_slot_17" => Some(GameAction::HotbarSlot17),
            "hotbar_slot_18" => Some(GameAction::HotbarSlot18),
            "hotbar_slot_19" => Some(GameAction::HotbarSlot19),
            "hotbar_slot_20" => Some(GameAction::HotbarSlot20),
            "hotbar_slot_21" => Some(GameAction::HotbarSlot21),
            "hotbar_slot_22" => Some(GameAction::HotbarSlot22),
            "hotbar_slot_23" => Some(GameAction::HotbarSlot23),
            "hotbar_slot_24" => Some(GameAction::HotbarSlot24),
            "hotbar_slot_25" => Some(GameAction::HotbarSlot25),
            "hotbar_slot_26" => Some(GameAction::HotbarSlot26),
            "hotbar_slot_27" => Some(GameAction::HotbarSlot27),
            "hotbar_slot_28" => Some(GameAction::HotbarSlot28),
            "hotbar_slot_29" => Some(GameAction::HotbarSlot29),
            "hotbar_slot_30" => Some(GameAction::HotbarSlot30),
            "hotbar_slot_31" => Some(GameAction::HotbarSlot31),
            "hotbar_slot_32" => Some(GameAction::HotbarSlot32),
            "hotbar_slot_33" => Some(GameAction::HotbarSlot33),
            "hotbar_slot_34" => Some(GameAction::HotbarSlot34),
            "hotbar_slot_35" => Some(GameAction::HotbarSlot35),
            "hotbar_slot_36" => Some(GameAction::HotbarSlot36),
            "hotbar_slot_37" => Some(GameAction::HotbarSlot37),
            "hotbar_slot_38" => Some(GameAction::HotbarSlot38),
            "hotbar_slot_39" => Some(GameAction::HotbarSlot39),
            "hotbar_slot_40" => Some(GameAction::HotbarSlot40),
            "hotbar_slot_41" => Some(GameAction::HotbarSlot41),
            "hotbar_slot_42" => Some(GameAction::HotbarSlot42),
            "hotbar_slot_43" => Some(GameAction::HotbarSlot43),
            "hotbar_slot_44" => Some(GameAction::HotbarSlot44),
            "hotbar_slot_45" => Some(GameAction::HotbarSlot45),
            "hotbar_slot_46" => Some(GameAction::HotbarSlot46),
            "hotbar_slot_47" => Some(GameAction::HotbarSlot47),
            "hotbar_slot_48" => Some(GameAction::HotbarSlot48),
            "switch_to_inventory" => Some(GameAction::SwitchToInventory),
            "switch_to_skills" => Some(GameAction::SwitchToSkills),
            "switch_to_spells" => Some(GameAction::SwitchToSpells),
            "switch_to_hotbar_1" => Some(GameAction::SwitchToHotbar1),
            "switch_to_hotbar_2" => Some(GameAction::SwitchToHotbar2),
            "switch_to_hotbar_3" => Some(GameAction::SwitchToHotbar3),
            _ => None,
        }
    }

    pub fn label(&self) -> &'static str {
        match self {
            GameAction::MoveUp => "Move Up",
            GameAction::MoveDown => "Move Down",
            GameAction::MoveLeft => "Move Left",
            GameAction::MoveRight => "Move Right",
            GameAction::Inventory => "Inventory",
            GameAction::Skills => "Skills",
            GameAction::Spells => "Spells",
            GameAction::Settings => "Settings",
            GameAction::Refresh => "Refresh",
            GameAction::ToggleOverview => "Tab overview",
            GameAction::BasicAttack => "Basic Attack",
            GameAction::AutoAttackToggle => "Auto Attack Toggle",
            GameAction::ItemPickupBelow => "Item Pickup",
            GameAction::HotbarSlot1 => "Slot 1",
            GameAction::HotbarSlot2 => "Slot 2",
            GameAction::HotbarSlot3 => "Slot 3",
            GameAction::HotbarSlot4 => "Slot 4",
            GameAction::HotbarSlot5 => "Slot 5",
            GameAction::HotbarSlot6 => "Slot 6",
            GameAction::HotbarSlot7 => "Slot 7",
            GameAction::HotbarSlot8 => "Slot 8",
            GameAction::HotbarSlot9 => "Slot 9",
            GameAction::HotbarSlot10 => "Slot 10",
            GameAction::HotbarSlot11 => "Slot 11",
            GameAction::HotbarSlot12 => "Slot 12",
            GameAction::HotbarSlot13 => "Slot 13",
            GameAction::HotbarSlot14 => "Slot 14",
            GameAction::HotbarSlot15 => "Slot 15",
            GameAction::HotbarSlot16 => "Slot 16",
            GameAction::HotbarSlot17 => "Slot 17",
            GameAction::HotbarSlot18 => "Slot 18",
            GameAction::HotbarSlot19 => "Slot 19",
            GameAction::HotbarSlot20 => "Slot 20",
            GameAction::HotbarSlot21 => "Slot 21",
            GameAction::HotbarSlot22 => "Slot 22",
            GameAction::HotbarSlot23 => "Slot 23",
            GameAction::HotbarSlot24 => "Slot 24",
            GameAction::HotbarSlot25 => "Slot 25",
            GameAction::HotbarSlot26 => "Slot 26",
            GameAction::HotbarSlot27 => "Slot 27",
            GameAction::HotbarSlot28 => "Slot 28",
            GameAction::HotbarSlot29 => "Slot 29",
            GameAction::HotbarSlot30 => "Slot 30",
            GameAction::HotbarSlot31 => "Slot 31",
            GameAction::HotbarSlot32 => "Slot 32",
            GameAction::HotbarSlot33 => "Slot 33",
            GameAction::HotbarSlot34 => "Slot 34",
            GameAction::HotbarSlot35 => "Slot 35",
            GameAction::HotbarSlot36 => "Slot 36",
            GameAction::HotbarSlot37 => "Slot 37",
            GameAction::HotbarSlot38 => "Slot 38",
            GameAction::HotbarSlot39 => "Slot 39",
            GameAction::HotbarSlot40 => "Slot 40",
            GameAction::HotbarSlot41 => "Slot 41",
            GameAction::HotbarSlot42 => "Slot 42",
            GameAction::HotbarSlot43 => "Slot 43",
            GameAction::HotbarSlot44 => "Slot 44",
            GameAction::HotbarSlot45 => "Slot 45",
            GameAction::HotbarSlot46 => "Slot 46",
            GameAction::HotbarSlot47 => "Slot 47",
            GameAction::HotbarSlot48 => "Slot 48",
            GameAction::SwitchToInventory => "Inventory Panel",
            GameAction::SwitchToSkills => "Skills Panel",
            GameAction::SwitchToSpells => "Spells Panel",
            GameAction::SwitchToHotbar1 => "Hotbar 1",
            GameAction::SwitchToHotbar2 => "Hotbar 2",
            GameAction::SwitchToHotbar3 => "Hotbar 3",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::GameAction;

    #[test]
    fn toggle_overview_action_round_trips() {
        assert_eq!(GameAction::ToggleOverview.action_id(), "toggle_overview");
        assert_eq!(
            GameAction::from_action_id("toggle_overview"),
            Some(GameAction::ToggleOverview)
        );
        assert!(GameAction::all().contains(&GameAction::ToggleOverview));
    }
}
