[package]
name = "game-ui"
version.workspace = true
edition.workspace = true
build = "build.rs"

[dependencies]
game-types.workspace = true
formats.workspace = true
rendering.workspace = true
packets.workspace = true
regex = "1"

bevy.workspace = true
wgpu.workspace = true
smol = "2.0"
crossbeam-channel.workspace = true
i-slint-core.workspace = true
slint.workspace = true
oxicode.workspace = true
serde.workspace = true

[build-dependencies]
slint-build = "1.17.0"
