[package]
name = "packets"
version.workspace = true
edition.workspace = true

[lib]
name = "packets"
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
async-std.workspace = true
crc.workspace = true
byteorder.workspace = true
num_enum.workspace = true
md5.workspace = true
encoding.workspace = true
rand.workspace = true
